pulse:
  oauth2:
    client-id: ${PULSE_CLIENT_ID:}
    client-secret: ${PULSE_CLIENT_SECRET:}
server:
  scheme: ${PULSE_REDIRECT_SERVER_SCHEME:http}
  host: ${PULSE_REDIRECT_SERVER_HOST:localhost}
  port: ${PULSE_REDIRECT_SERVER_PORT:8080}
cookie:
  domain: ${PULSE_COOKIE_DOMAIN:localhost}
spring:
  data:
    rest:
      base-path: /api
  jpa:
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.H2Dialect