liferay:
  oauth:
    application:
      external:
        reference:
          codes: pulse-micro-service-oauth-application-user-agent,pulse-micro-service-oauth-application-headless-server
    urls:
      excludes: /ready,/redirect,/c/*
logging:
  level:
    reactor:
      netty:
        http:
          client: INFO
    com:
      liferay:
        sales:
          engineering:
            pulse: DEBUG
pulse:
  cookie:
    domain: ${PULSE_COOKIE_DOMAIN:localhost}
  liferay:
    base-endpoint:
      scheme: ${LIFERAY_SERVER_SCHEME:http}
      host: ${LIFERAY_SERVER_HOST:localhost}
      port: ${LIFERAY_SERVER_PORT:8080}
server:
  port: 58080
spring:
  config:
    import:
      - optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/
      - optional:configtree:${LIFERAY_ROUTES_DXP}/
  data:
    rest:
      base-path: /api
  jpa:
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true