liferay:
  oauth:
    application:
      external:
        reference:
          # There's a bug in the library which prevents the use of spaces adjacent to the comma in this property
          codes: pulse-micro-service-oauth-application-user-agent,pulse-micro-service-oauth-application-headless-server
    urls:
      # The token url has been updated to include a prefix to allow glob matching
      excludes: /ready,/redirect,/c/*,/actuator/*
logging:
  level:
    reactor:
      netty:
        http:
          client: INFO
    com:
      liferay:
        sales:
          engineering:
            pulse: TRACE
    org:
      springframework:
        security: INFO
pulse:
  # When this is not set, Pulse will set the cookie domain name to the hostname in the HTTP host header.
  # This needs to be set in LXC SM because the microservice and Liferay service will be accessed over
  # two different subdomains, which share the same common domain. In this case, this value should be the
  # common domain
  cookie_domain: ${PULSE_COOKIE_DOMAIN:localhost}
  # The path of the cookie. It should start with a forward slash (/)
  cookie_path: ${PULSE_COOKIE_PATH:/}
  # The name of the cookie which will pass the campaign identifier (ERC)
  cookie_campaign_name: ${PULSE_COOKIE_NAME_CAMPAIGN:__pcId}
  # The name of the cookie which will pass the url token
  cookie_url_token_name: ${PULSE_COOKIE_NAME_CAMPAIGN:__pcUt}
  # The name of the cookie which will pass the campaign interaction identifier (ERC)
  cookie_campaign_interaction_name: ${PULSE_COOKIE_NAME_CAMPAIGN:__intId}
  # When this is set to true, Pulse will redirect to its own test endpoint. The content of the request will
  # be output to the logs
  test_redirect: ${PULSE_TEST_REDIRECT:false}
  cache_refresh_delay_ms: 10000
  cron_schedule: '0 0/15 * * * *'
  # When this is set to true, Pulse terminate if it is unable to load the campaign data from the Liferay Objects.
  startup_exception_close_context: ${PULSE_CLOSE_CONTEXT:true}
server:
  port: 58080
spring:
  config:
    import:
      - optional:configtree:${LIFERAY_ROUTES_CLIENT_EXTENSION}/
      - optional:configtree:${LIFERAY_ROUTES_DXP}/
  data:
    rest:
      base-path: /api
  jpa:
    open-in-view: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        dialect: org.hibernate.dialect.H2Dialect
  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: "*"